# ZSH

- name: install zshrc
  copy:
    src: zsh/zshrc
    dest: "~{{ item }}/.zshrc"
  with_items:
    - root
    - grant

- name: download oh-my-zsh
  git:
    repo: "{{ ohmyzsh_repo }}"
    dest: "~{{ item }}/{{ ohmyzsh_directory }}"
    force: yes
  with_items:
    - root
    - grant

- name: insert custom ohmyzsh config for user
  copy:
    src: "zsh/{{ item }}"
    dest: "~grant/{{ ohmyzsh_directory }}/custom/{{ item }}"
    backup: yes
  with_items:
    - aliases.zsh
    - environment.zsh
    - path.zsh
    - gt.zsh

- name: insert custom ohmyzsh config for root
  copy:
    src: "zsh/{{ item }}"
    dest: "/root/{{ ohmyzsh_directory }}/custom/{{ item }}"
    backup: yes
  with_items:
    - aliases.zsh
    - environment.zsh
    - path.zsh
    - gt.zsh

- name: "set user shell"
  user:
    name: "{{ item }}"
    shell: /usr/local/bin/zsh
  become: yes
  with_items:
    - root
    - grant
