---
- name: install common python
  package:
    name:
      - python2
      - python37
    state: present

# https://www.python.org/dev/peps/pep-0394/
- name: link version
  file:
    src: /usr/local/bin/python2
    dest: /usr/local/bin/python
    state: link

- name: link system
  file:
    src: /usr/local/bin/python
    dest: /usr/bin/python
    state: link

- name: install python tools
  package:
    name:
      - py27-pip
      - py37-pip
      - py27-virtualenv
      - py37-virtualenv
      - py27-virtualenvwrapper
    state: present

# @TODO . /usr/local/bin/virtualenvwrapper.sh
