---
- name: install common python
  package:
    name:
      - python39
    state: present

#- name: link system
#  file:
#    src: /usr/local/bin/python
#    dest: /usr/bin/python
#    state: link

- name: install python tools
  package:
    name:
      - py39-pip
      - py39-virtualenv
      - py39-sqlite3
    state: present

# @TODO . /usr/local/bin/virtualenvwrapper.sh
