---
- name: install cert
  copy:
    src: tars-ca.crt
    dest: /etc/ssl/tars-ca.crt
    owner: root
    group: wheel
    mode: 0644

- name: trust cert
  blockinfile:
    dest: /etc/ssl/cert.pem
    block: "{{ lookup('file', '/etc/ssl/tars-ca.crt') }}"
    insertafter: "##  End of file"
    backup: yes
