---
- name: sickchill
  hosts: all
  tasks:
    - git:
        repo: https://github.com/SickChill/SickChill
        dest: /usr/local/sickchill
      become: yes
      become_user: sickchill

    - file:
        path: "{{ item }}"
        state: directory
        owner: sickchill
        group: sickchill
      with_items:
        - /usr/local/sickchill
        - /var/sickchill
        - /var/sickchill/Logs

    - file:
        src: /usr/local/bin/git
        dest: /bin/git
        state: link

    - copy:
        src: /usr/local/sickchill/runscripts/init.freebsd
        dest: /usr/local/etc/rc.d/sickchill
        remote_src: yes
        mode: 0755

    - lineinfile:
        path: /etc/rc.conf
        line: "{{ item }}"
        insertafter: ^sickchill_enable*
      with_items:
        - sickchill_user="sickchill"
        - sickchill_group="sickchill"
        - sickchill_datadir="/var/sickchill"

    - file:
        src: /var/sickchill/Logs
        dest: /var/log/sickchill
        state: link

    - service:
        name: sickchill
        enabled: yes
